# Generated by Django 5.0.3 on 2024-03-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic_url',
            field=models.FileField(blank=True, upload_to='profile_pic/'),
        ),
    ]
