# Generated by Django 5.0.6 on 2024-06-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_networkedge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_pic_url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.FileField(blank=True, upload_to='profile_pic/'),
        ),
    ]
