# Generated by Django 5.0.3 on 2024-04-11 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_userpost_caption_text_alter_userpost_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='autho',
            new_name='author',
        ),
    ]
