# Generated by Django 5.0.3 on 2024-04-11 09:21

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_rename_autho_userpost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='media_file',
            field=models.FileField(upload_to=content.models.PostMedia.media_name),
        ),
    ]
