# Generated by Django 5.0.3 on 2024-04-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_postcomments_postlikes'),
        ('users', '0004_networkedge'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postlikes',
            unique_together={('post', 'liked_by')},
        ),
    ]
